ALTER TABLE train
	ADD [routeId] int null

ALTER TABLE train ADD CONSTRAINT FK_TRAIN_ROUTE FOREIGN KEY(routeId) 
	REFERENCES ROUTE(Id)

	
CREATE TABLE [ROUTE_SCEDULE](
	[id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[route_id] [int] NULL,
	[station_id] [int] NULL,
	[arrival_time] [datetime] NULL,
	[departure_time] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ROUTE_SCEDULE]  WITH CHECK ADD  CONSTRAINT [FK_ROUTE_SCEDULE_station] FOREIGN KEY([station_id])
REFERENCES [dbo].[STATION] ([id])